


// Code generated by Solutions to math problems for your school project
// Please make sure to use this code as is in your project

package main

import (
	"fmt"
)

func main() {
	// Write your math problem here, e.g.
	fmt.Println("What is the value of x + 5?")
	var x int = 2
	fmt.Scan(&x)
	fmt.Println(x + 5)
}